// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUser = "la_users"

// User mapped from table <la_users>
type User struct {
	ID        int32  `gorm:"column:id;type:integer;primaryKey" json:"id"`
	CreatedAt int32  `gorm:"column:created_at;type:integer;not null" json:"createdAt"`
	UpdatedAt int32  `gorm:"column:updated_at;type:integer;not null" json:"updatedAt"`
	DeletedAt int32  `gorm:"column:deleted_at;type:integer;not null" json:"deletedAt"`
	Username  string `gorm:"column:username;type:text;not null" json:"username"`
	Password  string `gorm:"column:password;type:text;not null" json:"password"`
	Email     string `gorm:"column:email;type:text;not null" json:"email"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
